server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://localhost/pms?serverTimezone=UTC
    username: pms
    password: pms
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
mybatis:
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: true
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
shiro:
  loginUrl: /user/login